#!/bin/sh
set -e

board=$(cat /sys/firmware/devicetree/base/model | awk '{print tolower($3)}')

if ! grep -q "${board}" /etc/apt/sources.list.d/vicharak.list; then
    echo "deb http://apt.vicharak.in/ stable main" > /etc/apt/sources.list.d/vicharak.list
    echo "deb http://apt.vicharak.in/ stable-${board} ${board}" >> /etc/apt/sources.list.d/vicharak.list
fi

echo "enable confugure service"
systemctl daemon-reload  
#systemctl enable --now configure-hotspot@access_recovery
#systemctl enable --now configure-hotspot@on_boot_hotspot
echo "enable confugure hotspot service"
exit 0
